[0m10:59:43.753853 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FCDC40690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FCDC426D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FCDC41A50>]}


============================== 10:59:43.779853 | a246b461-87fc-4768-9f75-3b7dda10fd3c ==============================
[0m10:59:43.779853 [info ] [MainThread]: Running with dbt=1.8.7
[0m10:59:43.782855 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:59:43.785852 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\dbt-dags\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:59:43.791856 [debug] [MainThread]: Command `dbt run` failed at 10:59:43.790853 after 0.41 seconds
[0m10:59:43.793853 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FCDC40690>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FCDC41A50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026FC7A6B050>]}
[0m10:59:43.795859 [debug] [MainThread]: Flushing usage events
[0m15:26:51.795337 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D2DE3AD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D2942F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D2CBD990>]}


============================== 15:26:51.805449 | cdb77879-d089-4248-b27e-46eea5f150d3 ==============================
[0m15:26:51.805449 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:26:51.807573 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:26:51.809856 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\dbt-dags\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:26:51.814445 [debug] [MainThread]: Command `dbt deps` failed at 15:26:51.813906 after 0.28 seconds
[0m15:26:51.816225 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210D2E3A850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210CC711810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210CC7117D0>]}
[0m15:26:51.818824 [debug] [MainThread]: Flushing usage events
[0m15:29:59.217418 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC419D1F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC419D2E50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC419836D0>]}


============================== 15:29:59.223461 | 812f6a09-9517-4de1-a9c3-0b6def195185 ==============================
[0m15:29:59.223461 [info ] [MainThread]: Running with dbt=1.8.7
[0m15:29:59.224689 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\hp\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:29:59.226197 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\hp\dbt-dags\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:29:59.228243 [debug] [MainThread]: Command `dbt deps` failed at 15:29:59.228243 after 0.12 seconds
[0m15:29:59.229204 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC419D1F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC4185D910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001EC40921510>]}
[0m15:29:59.230246 [debug] [MainThread]: Flushing usage events
